function patrolGhostMoves(points) {
    let nextPosition = points[1];
    return (thisGhost) => {
        if (((p1 = thisGhost.position), (p2 = nextPosition), p1.x === p2.x && p1.y === p2.y)) {
            const nextTargetIdx = points.indexOf(nextPosition) + 1;
            nextPosition = nextTargetIdx >= points.length ? points[0] : points[nextTargetIdx];
        }
        var p1, p2;
        return nextPosition;
    };
}
function getImmobileGhost(position) {
    return { position, getMoveTarget: () => position, canTurnAround: !1, velocity: 0 };
}
function getRandomItem(items) {
    if (1 === items.length) return items[0];
    var lengthArray;
    return items[
        (lengthArray = items.length) < 2 ? lengthArray : Math.floor(Math.random() * lengthArray)
    ];
}
var ghostsPaths = {
    maze1: [
        [
            {
                position: { x: 5, y: 3 },
                getMoveTarget: patrolGhostMoves([
                    { x: 5, y: 3 },
                    { x: 7, y: 3 },
                    { x: 7, y: 8 },
                    { x: 3, y: 8 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 22, y: 3 },
                getMoveTarget: patrolGhostMoves([
                    { x: 21, y: 3 },
                    { x: 24, y: 3 },
                    { x: 24, y: 8 },
                    { x: 21, y: 8 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 5, y: 20 },
                getMoveTarget: patrolGhostMoves([
                    { x: 5, y: 20 },
                    { x: 7, y: 20 },
                    { x: 7, y: 25 },
                    { x: 3, y: 25 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 22, y: 20 },
                getMoveTarget: patrolGhostMoves([
                    { x: 21, y: 20 },
                    { x: 24, y: 20 },
                    { x: 24, y: 25 },
                    { x: 21, y: 25 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
        ],
        [
            {
                position: { x: 0, y: 3 },
                getMoveTarget: patrolGhostMoves([
                    { x: 27, y: 3 },
                    { x: 0, y: 3 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 27, y: 25 },
                getMoveTarget: patrolGhostMoves([
                    { x: 0, y: 25 },
                    { x: 27, y: 25 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 3, y: 8 },
                getMoveTarget: patrolGhostMoves([
                    { x: 24, y: 8 },
                    { x: 3, y: 8 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 24, y: 20 },
                getMoveTarget: patrolGhostMoves([
                    { x: 3, y: 20 },
                    { x: 24, y: 20 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
        ],
        [
            {
                position: { x: 11, y: 11 },
                getMoveTarget: patrolGhostMoves([
                    { x: 14, y: 11 },
                    { x: 16, y: 11 },
                    { x: 16, y: 17 },
                    { x: 11, y: 17 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 3, y: 3 },
                getMoveTarget: patrolGhostMoves([
                    { x: 22, y: 3 },
                    { x: 24, y: 3 },
                    { x: 24, y: 8 },
                    { x: 3, y: 8 },
                    { x: 3, y: 3 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 3, y: 20 },
                getMoveTarget: patrolGhostMoves([
                    { x: 22, y: 20 },
                    { x: 24, y: 20 },
                    { x: 24, y: 25 },
                    { x: 3, y: 25 },
                    { x: 3, y: 20 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
        ],
    ],
    maze2: [
        [
            {
                position: { x: 2, y: 13 },
                getMoveTarget: patrolGhostMoves([
                    { x: 27, y: 14 },
                    { x: 2, y: 13 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 14, y: 2 },
                getMoveTarget: patrolGhostMoves([
                    { x: 13, y: 25 },
                    { x: 14, y: 2 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
        ],
        [
            {
                position: { x: 2, y: 2 },
                getMoveTarget: patrolGhostMoves([
                    { x: 14, y: 2 },
                    { x: 25, y: 2 },
                    { x: 25, y: 25 },
                    { x: 2, y: 25 },
                    { x: 2, y: 2 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 10, y: 10 },
                getMoveTarget: patrolGhostMoves([
                    { x: 14, y: 10 },
                    { x: 17, y: 10 },
                    { x: 17, y: 17 },
                    { x: 10, y: 17 },
                    { x: 10, y: 10 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 6, y: 6 },
                getMoveTarget: patrolGhostMoves([
                    { x: 14, y: 6 },
                    { x: 21, y: 6 },
                    { x: 21, y: 21 },
                    { x: 6, y: 21 },
                    { x: 6, y: 6 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
        ],
        [
            {
                position: { x: 2, y: 2 },
                getMoveTarget: patrolGhostMoves([
                    { x: 7, y: 2 },
                    { x: 14, y: 2 },
                    { x: 14, y: 13 },
                    { x: 2, y: 13 },
                    { x: 2, y: 2 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 25, y: 2 },
                getMoveTarget: patrolGhostMoves([
                    { x: 25, y: 14 },
                    { x: 14, y: 14 },
                    { x: 14, y: 2 },
                    { x: 25, y: 2 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 25, y: 14 },
                getMoveTarget: patrolGhostMoves([
                    { x: 25, y: 20 },
                    { x: 25, y: 25 },
                    { x: 13, y: 25 },
                    { x: 13, y: 14 },
                    { x: 25, y: 14 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 2, y: 13 },
                getMoveTarget: patrolGhostMoves([
                    { x: 7, y: 13 },
                    { x: 13, y: 13 },
                    { x: 13, y: 25 },
                    { x: 2, y: 25 },
                    { x: 2, y: 13 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
        ],
    ],
    maze3: [
        [
            {
                position: { x: 2, y: 2 },
                getMoveTarget: patrolGhostMoves([
                    { x: 5, y: 2 },
                    { x: 10, y: 2 },
                    { x: 10, y: 6 },
                    { x: 2, y: 6 },
                    { x: 2, y: 2 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 25, y: 2 },
                getMoveTarget: patrolGhostMoves([
                    { x: 23, y: 2 },
                    { x: 18, y: 2 },
                    { x: 18, y: 6 },
                    { x: 25, y: 6 },
                    { x: 25, y: 2 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 2, y: 24 },
                getMoveTarget: patrolGhostMoves([
                    { x: 4, y: 24 },
                    { x: 8, y: 24 },
                    { x: 8, y: 14 },
                    { x: 2, y: 14 },
                    { x: 2, y: 24 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 25, y: 24 },
                getMoveTarget: patrolGhostMoves([
                    { x: 25, y: 24 },
                    { x: 20, y: 24 },
                    { x: 20, y: 14 },
                    { x: 25, y: 14 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
        ],
        [
            {
                position: { x: 2, y: 2 },
                getMoveTarget: patrolGhostMoves([
                    { x: 25, y: 2 },
                    { x: 2, y: 2 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 25, y: 6 },
                getMoveTarget: patrolGhostMoves([
                    { x: 2, y: 6 },
                    { x: 25, y: 6 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 2, y: 14 },
                getMoveTarget: patrolGhostMoves([
                    { x: 25, y: 14 },
                    { x: 2, y: 14 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 25, y: 24 },
                getMoveTarget: patrolGhostMoves([
                    { x: 2, y: 24 },
                    { x: 25, y: 24 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
        ],
        [
            {
                position: { x: 2, y: 2 },
                getMoveTarget: patrolGhostMoves([
                    { x: 23, y: 2 },
                    { x: 25, y: 2 },
                    { x: 25, y: 6 },
                    { x: 2, y: 6 },
                    { x: 2, y: 2 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 2, y: 6 },
                getMoveTarget: patrolGhostMoves([
                    { x: 25, y: 6 },
                    { x: 25, y: 14 },
                    { x: 2, y: 14 },
                    { x: 2, y: 6 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 2, y: 14 },
                getMoveTarget: patrolGhostMoves([
                    { x: 23, y: 14 },
                    { x: 25, y: 14 },
                    { x: 25, y: 24 },
                    { x: 2, y: 24 },
                    { x: 2, y: 14 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
        ],
    ],
    maze4: [
        [
            {
                position: { x: 3, y: 3 },
                getMoveTarget: patrolGhostMoves([
                    { x: 24, y: 3 },
                    { x: 3, y: 3 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 24, y: 7 },
                getMoveTarget: patrolGhostMoves([
                    { x: 3, y: 7 },
                    { x: 24, y: 7 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 3, y: 20 },
                getMoveTarget: patrolGhostMoves([
                    { x: 24, y: 20 },
                    { x: 3, y: 20 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 24, y: 24 },
                getMoveTarget: patrolGhostMoves([
                    { x: 3, y: 24 },
                    { x: 24, y: 24 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
        ],
        [
            {
                position: { x: 3, y: 3 },
                getMoveTarget: patrolGhostMoves([
                    { x: 3, y: 24 },
                    { x: 3, y: 3 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 7, y: 24 },
                getMoveTarget: patrolGhostMoves([
                    { x: 7, y: 3 },
                    { x: 7, y: 24 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 20, y: 3 },
                getMoveTarget: patrolGhostMoves([
                    { x: 20, y: 24 },
                    { x: 20, y: 3 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 24, y: 24 },
                getMoveTarget: patrolGhostMoves([
                    { x: 24, y: 3 },
                    { x: 24, y: 24 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
        ],
        [
            {
                position: { x: 3, y: 3 },
                getMoveTarget: patrolGhostMoves([
                    { x: 21, y: 3 },
                    { x: 24, y: 3 },
                    { x: 24, y: 7 },
                    { x: 3, y: 7 },
                    { x: 3, y: 3 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 24, y: 3 },
                getMoveTarget: patrolGhostMoves([
                    { x: 24, y: 24 },
                    { x: 20, y: 24 },
                    { x: 20, y: 3 },
                    { x: 24, y: 3 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 24, y: 24 },
                getMoveTarget: patrolGhostMoves([
                    { x: 6, y: 24 },
                    { x: 3, y: 24 },
                    { x: 3, y: 20 },
                    { x: 24, y: 20 },
                    { x: 24, y: 24 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 3, y: 24 },
                getMoveTarget: patrolGhostMoves([
                    { x: 3, y: 3 },
                    { x: 7, y: 3 },
                    { x: 7, y: 24 },
                    { x: 3, y: 24 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
        ],
    ],
    maze5: [
        [
            {
                position: { x: 0, y: 0 },
                getMoveTarget: patrolGhostMoves([
                    { x: 27, y: 27 },
                    { x: 0, y: 0 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 27, y: 0 },
                getMoveTarget: patrolGhostMoves([
                    { x: 0, y: 27 },
                    { x: 27, y: 0 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 3, y: 3 },
                getMoveTarget: patrolGhostMoves([
                    { x: 24, y: 3 },
                    { x: 25, y: 3 },
                    { x: 25, y: 24 },
                    { x: 3, y: 24 },
                    { x: 3, y: 3 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
        ],
        [
            {
                position: { x: 3, y: 3 },
                getMoveTarget: patrolGhostMoves([
                    { x: 5, y: 6 },
                    { x: 13, y: 14 },
                    { x: 3, y: 14 },
                    { x: 3, y: 3 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 25, y: 3 },
                getMoveTarget: patrolGhostMoves([
                    { x: 24, y: 4 },
                    { x: 14, y: 14 },
                    { x: 25, y: 14 },
                    { x: 25, y: 3 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 3, y: 24 },
                getMoveTarget: patrolGhostMoves([
                    { x: 4, y: 23 },
                    { x: 13, y: 14 },
                    { x: 3, y: 14 },
                    { x: 3, y: 24 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 25, y: 24 },
                getMoveTarget: patrolGhostMoves([
                    { x: 24, y: 24 },
                    { x: 14, y: 14 },
                    { x: 24, y: 14 },
                    { x: 25, y: 24 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
        ],
        [
            {
                position: { x: 0, y: 14 },
                getMoveTarget: patrolGhostMoves([
                    { x: 27, y: 14 },
                    { x: 0, y: 14 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 3, y: 3 },
                getMoveTarget: patrolGhostMoves([
                    { x: 14, y: 3 },
                    { x: 25, y: 3 },
                    { x: 25, y: 24 },
                    { x: 3, y: 24 },
                    { x: 3, y: 3 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
        ],
    ],
    maze6: [
        [
            {
                position: { x: 3, y: 3 },
                getMoveTarget: patrolGhostMoves([
                    { x: 5, y: 3 },
                    { x: 7, y: 3 },
                    { x: 7, y: 7 },
                    { x: 3, y: 7 },
                    { x: 3, y: 3 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 20, y: 3 },
                getMoveTarget: patrolGhostMoves([
                    { x: 22, y: 3 },
                    { x: 24, y: 3 },
                    { x: 24, y: 9 },
                    { x: 20, y: 9 },
                    { x: 20, y: 3 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 20, y: 20 },
                getMoveTarget: patrolGhostMoves([
                    { x: 22, y: 20 },
                    { x: 24, y: 20 },
                    { x: 24, y: 24 },
                    { x: 20, y: 24 },
                    { x: 20, y: 20 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 3, y: 24 },
                getMoveTarget: patrolGhostMoves([
                    { x: 3, y: 18 },
                    { x: 7, y: 18 },
                    { x: 7, y: 24 },
                    { x: 3, y: 24 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
        ],
        [
            {
                position: { x: 3, y: 3 },
                getMoveTarget: patrolGhostMoves([
                    { x: 24, y: 3 },
                    { x: 3, y: 3 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 24, y: 3 },
                getMoveTarget: patrolGhostMoves([
                    { x: 24, y: 24 },
                    { x: 24, y: 3 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 24, y: 24 },
                getMoveTarget: patrolGhostMoves([
                    { x: 3, y: 24 },
                    { x: 24, y: 24 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 3, y: 24 },
                getMoveTarget: patrolGhostMoves([
                    { x: 3, y: 3 },
                    { x: 3, y: 24 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
        ],
        [
            {
                position: { x: 3, y: 3 },
                getMoveTarget: patrolGhostMoves([
                    { x: 14, y: 3 },
                    { x: 24, y: 3 },
                    { x: 24, y: 24 },
                    { x: 3, y: 24 },
                    { x: 3, y: 3 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 24, y: 3 },
                getMoveTarget: patrolGhostMoves([
                    { x: 24, y: 14 },
                    { x: 24, y: 24 },
                    { x: 3, y: 24 },
                    { x: 3, y: 3 },
                    { x: 24, y: 3 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 24, y: 24 },
                getMoveTarget: patrolGhostMoves([
                    { x: 14, y: 24 },
                    { x: 3, y: 24 },
                    { x: 3, y: 3 },
                    { x: 24, y: 3 },
                    { x: 24, y: 24 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 3, y: 24 },
                getMoveTarget: patrolGhostMoves([
                    { x: 3, y: 14 },
                    { x: 3, y: 3 },
                    { x: 24, y: 3 },
                    { x: 24, y: 24 },
                    { x: 3, y: 24 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
        ],
    ],
    maze7: [
        [
            {
                position: { x: 0, y: 12 },
                getMoveTarget: patrolGhostMoves([
                    { x: 27, y: 12 },
                    { x: 0, y: 12 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 27, y: 15 },
                getMoveTarget: patrolGhostMoves([
                    { x: 0, y: 15 },
                    { x: 27, y: 15 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 11, y: 0 },
                getMoveTarget: patrolGhostMoves([
                    { x: 11, y: 27 },
                    { x: 11, y: 0 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 16, y: 27 },
                getMoveTarget: patrolGhostMoves([
                    { x: 16, y: 0 },
                    { x: 16, y: 27 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
        ],
        [
            {
                position: { x: 2, y: 2 },
                getMoveTarget: patrolGhostMoves([
                    { x: 5, y: 2 },
                    { x: 7, y: 2 },
                    { x: 7, y: 12 },
                    { x: 2, y: 12 },
                    { x: 2, y: 2 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 20, y: 2 },
                getMoveTarget: patrolGhostMoves([
                    { x: 23, y: 2 },
                    { x: 25, y: 2 },
                    { x: 25, y: 12 },
                    { x: 20, y: 12 },
                    { x: 20, y: 2 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 2, y: 15 },
                getMoveTarget: patrolGhostMoves([
                    { x: 5, y: 15 },
                    { x: 7, y: 15 },
                    { x: 7, y: 25 },
                    { x: 2, y: 25 },
                    { x: 2, y: 15 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 20, y: 15 },
                getMoveTarget: patrolGhostMoves([
                    { x: 23, y: 15 },
                    { x: 25, y: 15 },
                    { x: 25, y: 25 },
                    { x: 20, y: 25 },
                    { x: 20, y: 15 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
        ],
        [
            {
                position: { x: 2, y: 2 },
                getMoveTarget: patrolGhostMoves([
                    { x: 5, y: 2 },
                    { x: 7, y: 2 },
                    { x: 7, y: 25 },
                    { x: 2, y: 25 },
                    { x: 2, y: 2 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 20, y: 2 },
                getMoveTarget: patrolGhostMoves([
                    { x: 23, y: 2 },
                    { x: 25, y: 2 },
                    { x: 25, y: 25 },
                    { x: 20, y: 25 },
                    { x: 20, y: 2 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 2, y: 12 },
                getMoveTarget: patrolGhostMoves([
                    { x: 14, y: 12 },
                    { x: 25, y: 12 },
                    { x: 25, y: 10 },
                    { x: 2, y: 10 },
                    { x: 2, y: 12 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 2, y: 15 },
                getMoveTarget: patrolGhostMoves([
                    { x: 14, y: 15 },
                    { x: 25, y: 15 },
                    { x: 25, y: 17 },
                    { x: 2, y: 17 },
                    { x: 2, y: 15 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
        ],
    ],
    maze8: [
        [
            {
                position: { x: 0, y: 2 },
                getMoveTarget: patrolGhostMoves([
                    { x: 27, y: 2 },
                    { x: 0, y: 2 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 0, y: 18 },
                getMoveTarget: patrolGhostMoves([
                    { x: 10, y: 18 },
                    { x: 10, y: 15 },
                    { x: 17, y: 15 },
                    { x: 17, y: 18 },
                    { x: 27, y: 18 },
                    { x: 17, y: 18 },
                    { x: 17, y: 21 },
                    { x: 10, y: 21 },
                    { x: 0, y: 18 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 0, y: 9 },
                getMoveTarget: patrolGhostMoves([
                    { x: 11, y: 9 },
                    { x: 11, y: 6 },
                    { x: 16, y: 6 },
                    { x: 16, y: 9 },
                    { x: 27, y: 9 },
                    { x: 16, y: 9 },
                    { x: 16, y: 13 },
                    { x: 11, y: 13 },
                    { x: 11, y: 9 },
                    { x: 0, y: 9 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 0, y: 23 },
                getMoveTarget: patrolGhostMoves([
                    { x: 27, y: 23 },
                    { x: 0, y: 23 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
        ],
        [
            {
                position: { x: 0, y: 2 },
                getMoveTarget: patrolGhostMoves([
                    { x: 27, y: 2 },
                    { x: 0, y: 2 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 27, y: 23 },
                getMoveTarget: patrolGhostMoves([
                    { x: 0, y: 23 },
                    { x: 27, y: 23 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 6, y: 0 },
                getMoveTarget: patrolGhostMoves([
                    { x: 6, y: 27 },
                    { x: 6, y: 0 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 21, y: 27 },
                getMoveTarget: patrolGhostMoves([
                    { x: 21, y: 0 },
                    { x: 21, y: 27 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
        ],
        [
            {
                position: { x: 2, y: 2 },
                getMoveTarget: patrolGhostMoves([
                    { x: 9, y: 2 },
                    { x: 11, y: 2 },
                    { x: 11, y: 9 },
                    { x: 2, y: 9 },
                    { x: 2, y: 2 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 25, y: 2 },
                getMoveTarget: patrolGhostMoves([
                    { x: 18, y: 2 },
                    { x: 16, y: 2 },
                    { x: 16, y: 9 },
                    { x: 25, y: 9 },
                    { x: 25, y: 2 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 6, y: 13 },
                getMoveTarget: patrolGhostMoves([
                    { x: 21, y: 13 },
                    { x: 21, y: 23 },
                    { x: 6, y: 23 },
                    { x: 6, y: 13 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
        ],
    ],
    maze9: [
        [
            {
                position: { x: 2, y: 2 },
                getMoveTarget: patrolGhostMoves([
                    { x: 6, y: 2 },
                    { x: 8, y: 2 },
                    { x: 8, y: 8 },
                    { x: 2, y: 8 },
                    { x: 2, y: 2 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 25, y: 2 },
                getMoveTarget: patrolGhostMoves([
                    { x: 23, y: 2 },
                    { x: 19, y: 2 },
                    { x: 19, y: 8 },
                    { x: 25, y: 8 },
                    { x: 25, y: 2 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 2, y: 19 },
                getMoveTarget: patrolGhostMoves([
                    { x: 6, y: 19 },
                    { x: 8, y: 19 },
                    { x: 8, y: 25 },
                    { x: 2, y: 25 },
                    { x: 2, y: 19 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 25, y: 19 },
                getMoveTarget: patrolGhostMoves([
                    { x: 23, y: 19 },
                    { x: 19, y: 19 },
                    { x: 19, y: 25 },
                    { x: 25, y: 25 },
                    { x: 25, y: 19 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
        ],
        [
            {
                position: { x: 8, y: 8 },
                getMoveTarget: patrolGhostMoves([
                    { x: 14, y: 8 },
                    { x: 19, y: 8 },
                    { x: 19, y: 19 },
                    { x: 8, y: 19 },
                    { x: 8, y: 8 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 2, y: 12 },
                getMoveTarget: patrolGhostMoves([
                    { x: 6, y: 12 },
                    { x: 8, y: 12 },
                    { x: 8, y: 15 },
                    { x: 2, y: 15 },
                    { x: 2, y: 12 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 25, y: 12 },
                getMoveTarget: patrolGhostMoves([
                    { x: 23, y: 12 },
                    { x: 19, y: 12 },
                    { x: 19, y: 15 },
                    { x: 25, y: 15 },
                    { x: 25, y: 12 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
        ],
        [
            {
                position: { x: 8, y: 8 },
                getMoveTarget: patrolGhostMoves([
                    { x: 14, y: 8 },
                    { x: 19, y: 8 },
                    { x: 19, y: 19 },
                    { x: 8, y: 19 },
                    { x: 8, y: 8 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 2, y: 12 },
                getMoveTarget: patrolGhostMoves([
                    { x: 6, y: 12 },
                    { x: 8, y: 12 },
                    { x: 8, y: 15 },
                    { x: 2, y: 15 },
                    { x: 2, y: 12 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 25, y: 12 },
                getMoveTarget: patrolGhostMoves([
                    { x: 23, y: 12 },
                    { x: 19, y: 12 },
                    { x: 19, y: 15 },
                    { x: 25, y: 15 },
                    { x: 25, y: 12 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 12, y: 2 },
                getMoveTarget: patrolGhostMoves([
                    { x: 14, y: 2 },
                    { x: 15, y: 2 },
                    { x: 15, y: 8 },
                    { x: 12, y: 8 },
                    { x: 12, y: 2 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 12, y: 19 },
                getMoveTarget: patrolGhostMoves([
                    { x: 14, y: 19 },
                    { x: 15, y: 19 },
                    { x: 15, y: 25 },
                    { x: 12, y: 25 },
                    { x: 12, y: 19 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
        ],
    ],
    maze10: [
        [
            {
                position: { x: 2, y: 2 },
                getMoveTarget: patrolGhostMoves([
                    { x: 25, y: 2 },
                    { x: 2, y: 2 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 25, y: 4 },
                getMoveTarget: patrolGhostMoves([
                    { x: 2, y: 4 },
                    { x: 25, y: 4 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 2, y: 7 },
                getMoveTarget: patrolGhostMoves([
                    { x: 25, y: 7 },
                    { x: 2, y: 7 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 25, y: 11 },
                getMoveTarget: patrolGhostMoves([
                    { x: 2, y: 11 },
                    { x: 25, y: 11 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 2, y: 16 },
                getMoveTarget: patrolGhostMoves([
                    { x: 25, y: 16 },
                    { x: 2, y: 16 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 25, y: 20 },
                getMoveTarget: patrolGhostMoves([
                    { x: 2, y: 20 },
                    { x: 25, y: 20 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 2, y: 23 },
                getMoveTarget: patrolGhostMoves([
                    { x: 25, y: 23 },
                    { x: 2, y: 23 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 25, y: 25 },
                getMoveTarget: patrolGhostMoves([
                    { x: 2, y: 25 },
                    { x: 25, y: 25 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
        ],
        [
            {
                position: { x: 2, y: 2 },
                getMoveTarget: patrolGhostMoves([
                    { x: 14, y: 2 },
                    { x: 25, y: 2 },
                    { x: 25, y: 4 },
                    { x: 2, y: 4 },
                    { x: 2, y: 2 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 25, y: 7 },
                getMoveTarget: patrolGhostMoves([
                    { x: 14, y: 7 },
                    { x: 2, y: 7 },
                    { x: 2, y: 11 },
                    { x: 25, y: 11 },
                    { x: 25, y: 7 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 2, y: 16 },
                getMoveTarget: patrolGhostMoves([
                    { x: 14, y: 16 },
                    { x: 25, y: 16 },
                    { x: 25, y: 20 },
                    { x: 2, y: 20 },
                    { x: 2, y: 16 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 25, y: 23 },
                getMoveTarget: patrolGhostMoves([
                    { x: 14, y: 23 },
                    { x: 2, y: 23 },
                    { x: 2, y: 25 },
                    { x: 25, y: 25 },
                    { x: 25, y: 23 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 2, y: 2 },
                getMoveTarget: patrolGhostMoves([
                    { x: 14, y: 2 },
                    { x: 25, y: 2 },
                    { x: 25, y: 25 },
                    { x: 2, y: 25 },
                    { x: 2, y: 2 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
        ],
        [
            {
                position: { x: 2, y: 2 },
                getMoveTarget: patrolGhostMoves([
                    { x: 8, y: 2 },
                    { x: 12, y: 2 },
                    { x: 12, y: 4 },
                    { x: 11, y: 4 },
                    { x: 11, y: 7 },
                    { x: 10, y: 7 },
                    { x: 10, y: 11 },
                    { x: 2, y: 11 },
                    { x: 2, y: 2 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 25, y: 2 },
                getMoveTarget: patrolGhostMoves([
                    { x: 21, y: 2 },
                    { x: 15, y: 2 },
                    { x: 15, y: 4 },
                    { x: 16, y: 4 },
                    { x: 16, y: 7 },
                    { x: 17, y: 7 },
                    { x: 17, y: 11 },
                    { x: 25, y: 11 },
                    { x: 25, y: 2 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 2, y: 25 },
                getMoveTarget: patrolGhostMoves([
                    { x: 8, y: 25 },
                    { x: 12, y: 25 },
                    { x: 12, y: 23 },
                    { x: 11, y: 23 },
                    { x: 11, y: 20 },
                    { x: 10, y: 20 },
                    { x: 10, y: 16 },
                    { x: 2, y: 16 },
                    { x: 2, y: 25 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 25, y: 25 },
                getMoveTarget: patrolGhostMoves([
                    { x: 21, y: 25 },
                    { x: 15, y: 25 },
                    { x: 15, y: 23 },
                    { x: 16, y: 23 },
                    { x: 16, y: 20 },
                    { x: 17, y: 20 },
                    { x: 17, y: 16 },
                    { x: 25, y: 16 },
                    { x: 25, y: 25 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
            {
                position: { x: 12, y: 9 },
                getMoveTarget: patrolGhostMoves([
                    { x: 13, y: 9 },
                    { x: 15, y: 9 },
                    { x: 15, y: 18 },
                    { x: 12, y: 18 },
                    { x: 12, y: 9 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
        ],
    ],
};
var secondLevel = [
    {
        mazeArray: [
            ['XXXXXXXXXXXXXXoXXXXXXXXXXXXX'],
            ['X oooooooooooooooooooooooooX'],
            ['XoXoXXoXXXXXXXoXXXXXXoXXoXoX'],
            ['XoXoXXoXXooooooooooXXoXXoXoX'],
            ['XoXoXXoXXXXXXXXXXXoXXoXXoXoX'],
            ['XoXoXXoXXooooooooooXXoXXoXoX'],
            ['XoXoXXoXXoXXXXXXXXXXXoXXoXoX'],
            ['XoXoXXoXXooooo ooooXXoXXoXoX'],
            ['XoXoXXoXXoXXXXXXXXoXXoXXoXoX'],
            ['XoXoXXoXXooooooooooXXoXXoXoX'],
            ['XoXoXXoXXXXXXXoXXXXXXoXXoXoX'],
            ['XoXoXXoXXXXXXXoXXXXXXoXXoXoX'],
            ['XoXoXXooooXXoooooXXoooXXoXoX'],
            ['ooooXXXXXoXXoooooXXoXXXXoooo'],
            ['XoX oooXXoXXoooooXXoXXoooXoX'],
            ['XoXXoXoXXoXXoo ooXXoXXoXXXoX'],
            ['XoXXoXoXXoXXoooooXXoXXoXXXoX'],
            ['XoXXoXoXXoXXoooooXXoXXoXXXoX'],
            ['XoXXoXoXXoXXoooooXXoXXoXXXoX'],
            ['XoXXoXoXXoXXXXXXXXXoXXoXXXoX'],
            ['XoXXoXoXXoX ooooooXoXXoXXXoX'],
            ['XoXXoXoXXoXoXoooooXoXXoXXXoX'],
            ['XoXXoXoXXoXoooooooXoXXoXXXoX'],
            ['XoXXoXoXXoXXXXXXXoXoXXoXXXoX'],
            ['XoXXoXoXXoXoooooooXoXXoXXXoX'],
            ['XoXXoXoXXoXXXXoXXXXoXXoXXXoX'],
            ['Xooooooooooooooooooooooooo X'],
            ['XXXXXXXXXXXXXXoXXXXXXXXXXXXX'],
        ],
        pacman: { position: { x: 11, y: 20 } },
        ghosts: [
            getImmobileGhost({ x: 1, y: 1 }),
            getImmobileGhost({ x: 26, y: 26 }),
            getImmobileGhost({ x: 14, y: 15 }),
            getImmobileGhost({ x: 14, y: 7 }),
            getImmobileGhost({ x: 3, y: 14 }),
        ],
    },
    {
        mazeArray: [
            ['XXXXXXXXXXoXXXXXXoXXXXXXXXXX'],
            ['XooooooooXooooooooXooooooooX'],
            ['XoXXoXXXoooXXooXXoooXXoXXXoX'],
            ['XooooooXoXooooooooXooooooooX'],
            ['XooXXXoXoXoXXooXXoXXoXoXXXoX'],
            ['XXoooXoooX XooooXoXooXoooooX'],
            ['XXXXoXoXoXoX oooXoXoXXXXoXXX'],
            ['oooooooXoooXXXXXXoo oooooooo'],
            ['XXXXoXoXoXooooooooXoXXoXoXXX'],
            ['XXoooXoooXooooooooXooooXoooX'],
            ['XooXXXoXoXoXX oXXoXoXXoXXXoX'],
            ['XooooooX oooooooooooXXoooooX'],
            ['XoXXoXXXoXoXXXXXXoXoXXXXXXoX'],
            ['XooooooooXooXooX oXooooooooX'],
            ['XXXXXXXXXXXoXooXoXXXXXXXXXXX'],
            ['XooooooooXooooooooXooooooooX'],
            ['XoXXoXXXoXooXXXXooXoXXoXXXoX'],
            ['XooooooXoooooooooooooooooooX'],
            ['XooXXXoXoXXXXooXXXXooXoXXXoX'],
            ['XXoooXoooXooooooooXooXoooooX'],
            ['XXXXoXoXoXooXooXooXoXXXXoXXX'],
            ['oooooo XooooXooXoooooooooooo'],
            ['XXXXoXoXoXoXXXXXXoXoXXoXoXXX'],
            ['XooooXoooXooooooooXooooXoooX'],
            ['XoXXXXoXoXoXXooXXoXoXXoXXXoX'],
            ['XoXXXXoXoXooXooXooXoXXoXXXoX'],
            ['XooooooXoooooo ooooooooooooX'],
            ['XXXXXXXXXXoXXXXXXoXXXXXXXXXX'],
        ],
        pacman: { position: { x: 12, y: 6 } },
        ghosts: [
            getImmobileGhost({ x: 14, y: 26 }),
            getImmobileGhost({ x: 16, y: 13 }),
            getImmobileGhost({ x: 8, y: 11 }),
            getImmobileGhost({ x: 19, y: 7 }),
            getImmobileGhost({ x: 13, y: 10 }),
            getImmobileGhost({ x: 6, y: 21 }),
            getImmobileGhost({ x: 10, y: 5 }),
        ],
    },
    {
        mazeArray: [
            ['XXXXXXXXXXXXXXoXXXXXXXXXXXXX'],
            ['XooooooooooooXoXoooooooooooX'],
            ['XoXXXoooXXXXoXoXoXXXXoooXXoX'],
            ['XoXXXXXoXooooXoXooooXoXXXXoX'],
            ['XoXXXXXoXoXXXXoXXXXoXoXXXXoX'],
            ['XoXooooooo ooooooo ooooooooX'],
            ['XoXoXXXoXXXoXXXXoXXXXoXXXoXX'],
            ['XoXoXXXoXXXoXXXXoXXXXoXXXoXX'],
            ['ooooooooooXoXXXXoXooo oooooo'],
            ['XXXXX XXXoXooooooXoXXXoXXXXX'],
            ['  XXXoXXX XoXXXXoXoXXXoXXX  '],
            ['  XooooooooooooooooooooooX  '],
            ['  XoXXXoXoXoXXoXoXoXoXXXoX  '],
            ['XXXoXXXoXoXoX oXoXoXoXXXoXXX'],
            ['ooooooooXoo XooX ooXoooooooo'],
            ['XXXoXXXoXoXoXooXoXoXoXXXoXXX'],
            ['  XoXXXoXoXoXXXXoXoXoXXXoX  '],
            ['  Xooooooooooooooooooo ooX  '],
            ['  XXXoXXXoXoXXXXoXoXXXoXXX  '],
            ['XXXXXoXXXoXooooooXoXXXoXXXXX'],
            ['ooooooooooXoXXXXoXo oooooooo'],
            ['XXoXXXXoXXXoXXXXoXXXXoXXXoXX'],
            ['XXoXXXXoXXXoXXXXoXXXXoXXXoXX'],
            ['XXoooooooooooo oooo oooooooX'],
            ['XXoXXXXoXoXXXXoXXXXoXoXXXXoX'],
            ['XXoXXXXoXooooXoXooooXoXXXXoX'],
            ['XXooooooXXXXoooooXXXXooooooX'],
            ['XXXXXXXXXXXXXXoXXXXXXXXXXXXX'],
        ],
        pacman: { position: { x: 13, y: 13 } },
        ghosts: [
            getImmobileGhost({ x: 14, y: 23 }),
            getImmobileGhost({ x: 16, y: 14 }),
            getImmobileGhost({ x: 9, y: 10 }),
            getImmobileGhost({ x: 5, y: 9 }),
            getImmobileGhost({ x: 21, y: 8 }),
            getImmobileGhost({ x: 19, y: 20 }),
            getImmobileGhost({ x: 22, y: 17 }),
            getImmobileGhost({ x: 19, y: 23 }),
            getImmobileGhost({ x: 11, y: 14 }),
            getImmobileGhost({ x: 10, y: 5 }),
            getImmobileGhost({ x: 18, y: 5 }),
        ],
    },
    {
        mazeArray: [
            ['XXXXXXXXXXXXXXXXXXXXXXXXXXXX'],
            ['X ooooXooooooooooooooXoooooX'],
            ['XoXoXoXoXXXXXoXXoXXXoXoXoXoX'],
            ['XoXoXoooXoooooXooXoooooXoXoX'],
            ['XoXoXXXXXoXXXXXoXXoXXXXXoXoX'],
            ['XoooooooooX ooXooooooXoooXoX'],
            ['XXXXX XXXoXoooXoXXoXoXoXXXoX'],
            ['XoooooXoooXoooooXXoXoXoXoooX'],
            ['XoXoXXXoXXXXXXXoXXoXoXoX XXX'],
            ['XoXoooXooooooooooooXoooXoooX'],
            ['XoXXXoXXXoXXXXXXXXXXXXXXXXoX'],
            ['XoooXoXoooXoooXoooXoooXooooX'],
            ['XoXoXoXoXXXoXoXoXoXoXoXoXXoX'],
            ['XoooooXoooooXoooXoooXooooooX'],
            ['XoXXXXXXXXXXXXoXXXXXXXXXXXoX'],
            ['XoooooXoooooXoooXo oXooooooX'],
            ['X XoXoXoXXXoXoXoXoXoXoXoXXoX'],
            ['XoooXoXoooXoooXoooXoooXooooX'],
            ['XoXXXoXXXoXXXXXXXXXXXXXXXXoX'],
            ['XoXoooXoooooooooo oXoooXoooX'],
            ['XoXoXXXoXXXXXXXoXXoXoXoXoXXX'],
            ['XoooooXoooXoooooXXoXoXoXoooX'],
            ['XXXXXoXXXoXoXXXoXXoXoXoXXXoX'],
            ['XoooooooooXoXXXo ooooXoooXoX'],
            ['XoXoXXXXXooooXXXoXoXXXXXoXoX'],
            ['XoXoXoooXXXXoXXXoXoXoooXoXoX'],
            ['XoooooXooooooo ooooooXoooooX'],
            ['XXXXXXXXXXXXXXXXXXXXXXXXXXXX'],
        ],
        pacman: { position: { x: 11, y: 5 } },
        ghosts: [
            getImmobileGhost({ x: 14, y: 26 }),
            getImmobileGhost({ x: 1, y: 1 }),
            getImmobileGhost({ x: 5, y: 6 }),
            getImmobileGhost({ x: 24, y: 8 }),
            getImmobileGhost({ x: 1, y: 16 }),
            getImmobileGhost({ x: 18, y: 15 }),
            getImmobileGhost({ x: 17, y: 19 }),
            getImmobileGhost({ x: 16, y: 23 }),
        ],
    },
    {
        mazeArray: [
            ['XXXXXXXXXXXXXXXXXXXXXXXXXXXX'],
            ['Xoooooo oooXXoooXXoooooooooX'],
            ['XoXXXXXoXXoXXoXoXXoXXoXXXXoX'],
            ['XoXXXXXoXXoXXoXoXXoXXoXXXXoX'],
            ['XoooooooXXoXXoXoXXoXXooooooX'],
            ['XoXXXXXoXXooooXooooXXoXXXXoX'],
            ['XoXXXXXoXXXXXoXoXXXXXoXXXXoX'],
            ['XoXXXXXoXXXXXoXoXXXXXoXXXXoX'],
            ['XoXXoooooooXXoXoXXooooooXXoX'],
            ['XoXXoXXXXoooooXoooo XXXoXXoX'],
            ['XoXXoXXXXooXXXXXXXooXXXoXXoX'],
            ['oooooooooooooo ooooooooooooo'],
            ['XoXXXXXXoXoXXXoXXXoXoXXXXXoX'],
            ['XoXXXXXXoXoX ooooXoXoXXXXXoX'],
            ['XooooooooXoXXXoXXXoXoooooo X'],
            ['XoXXXXXXoXoooooooooXoXXXXXoX'],
            ['X oooooXoXoXXXXXXXoXoXoooooX'],
            ['XoXXXXoXooooooXooooo XoXXXoX'],
            ['XooooooXoXXXXoXoXXXXoXoooooX'],
            ['XXXXXXoXoXooooo oooXoXoXXXXX'],
            ['oooooooX XoXXoXoXXoXoXoooooo'],
            ['XoXXXXXXoXoXXoXoXXoXoXXXXXoX'],
            ['XooooooooXoXXoXoXXoXoooooooX'],
            ['XoXoXXXXXXoXXoXoXXoXXXXXoXoX'],
            ['XoXooooooooXXoooXXoooooooXoX'],
            ['XoXXXXXXXXoXXXXXXXoXXXXXXXoX'],
            ['XooooooooooooooooooooooooooX'],
            ['XXXXXXXXXXXXXXXXXXXXXXXXXXXX'],
        ],
        pacman: { position: { x: 12, y: 13 } },
        ghosts: [
            getImmobileGhost({ x: 15, y: 19 }),
            getImmobileGhost({ x: 14, y: 11 }),
            getImmobileGhost({ x: 8, y: 20 }),
            getImmobileGhost({ x: 19, y: 9 }),
            getImmobileGhost({ x: 26, y: 14 }),
            getImmobileGhost({ x: 1, y: 16 }),
            getImmobileGhost({ x: 7, y: 1 }),
            getImmobileGhost({ x: 20, y: 17 }),
        ],
    },
];
var thirdLevel = [
    {
        pacman: { position: { x: 14, y: 14 } },
        mazeArray: [
            ['                            '],
            ['                            '],
            ['XXXXXXXXXXXXXXXXXXXXXXXXXXXX'],
            ['oooooooooooooooooooooooooooo'],
            ['XXXoXoXoXXXXXXXXXXXXoXoXoXXX'],
            ['  XoXoXoX          XoXoXoX  '],
            ['  XoXoXoX          XoXoXoX  '],
            ['  XoXXXoXXXXXXXXXXXXoXXXoX  '],
            ['  XooooooooooooooooooooooX  '],
            ['  XXXoXXXXXXoXXoXXXXXXoXXX  '],
            ['    XoX   XXoXXoXX   XoX    '],
            ['    XoX   XooooooX   XoX    '],
            ['    XoX   XoXXXXoX   XoX    '],
            ['    XoXXXXXoXXXXoXXXXXoX    '],
            ['    Xooooooooo ooooooooX    '],
            ['    XoXXXXXoXXXXoXXXXXoX    '],
            ['    XoX   XoXXXXoX   XoX    '],
            ['    XoX   XooooooX   XoX    '],
            ['    XoX   XXoXXoXX   XoX    '],
            ['  XXXoXXXXXXoXXoXXXXXXoXXX  '],
            ['  XooooooooooooooooooooooX  '],
            ['  XoXXXoXXXXXXXXXXXXoXXXoX  '],
            ['  XoXoXoX          XoXoXoX  '],
            ['  XoXoXoX          XoXoXoX  '],
            ['XXXoXoXoXXXXXXXXXXXXoXoXoXXX'],
            ['oooooooooooooooooooooooooooo'],
            ['XXXXXXXXXXXXXXXXXXXXXXXXXXXX'],
            ['                            '],
        ],
        ghosts: getRandomItem(ghostsPaths.maze1),
    },
    {
        pacman: { position: { x: 14, y: 14 } },
        mazeArray: [
            ['            XoX             '],
            [' XXXXXXXXXXXXoXXXXXXXXXXXXX '],
            [' XooooooooooooooooooooooooX '],
            [' XoXXXXXXXXXXXoXXXXXXXXXXoX '],
            [' XoX         XoX        XoX '],
            [' XoX XXXXXXXXXoXXXXXXXX XoX '],
            [' XoX XooooooooooooooooX XoX '],
            [' XoX XoXXXXXXXoXXXXXXoX XoX '],
            [' XoX XoX     XoX    XoX XoX '],
            [' XoX XoX XXXXXoXXXX XoX XoX '],
            [' XoX XoX XooooooooX XoX XoX '],
            [' XoX XoX XoXXXoXXoX XoX XoX '],
            [' XoXXXoXXXoXXXoXXoX XoX XoX '],
            ['XXoooooooooooooXXoXXXoXXXoXX'],
            ['oooXXXoXXXoXXo ooooooooooooo'],
            ['XXoX XoX XoXXoXXXoXXXoXXXoXX'],
            [' XoX XoX XoXXoXXXoX XoX XoX '],
            [' XoX XoX XooooooooX XoX XoX '],
            [' XoX XoX XXXXoXXXXX XoX XoX '],
            [' XoX XoX    XoX     XoX XoX '],
            [' XoX XoXXXXXXoXXXXXXXoX XoX '],
            [' XoX XooooooooooooooooX XoX '],
            [' XoX XXXXXXXXoXXXXXXXXX XoX '],
            [' XoX        XoX         XoX '],
            [' XoXXXXXXXXXXoXXXXXXXXXXXoX '],
            [' XooooooooooooooooooooooooX '],
            [' XXXXXXXXXXXXoXXXXXXXXXXXXX '],
            ['            XoX             '],
        ],
        ghosts: getRandomItem(ghostsPaths.maze2),
    },
    {
        pacman: { position: { x: 14, y: 14 } },
        mazeArray: [
            ['                            '],
            [' XXXXXXXXXXXXXXXXXXXXXXXXXX '],
            [' XooooooooooooooooooooooooX '],
            [' XoXXXoXXXoXXXXXXoXXXoXXXoX '],
            [' XoX XoX XoX    XoX XoX XoX '],
            [' XoXXXoXXXoXXXXXXoXXXoXXXoX '],
            [' XooooooooooooooooooooooooX '],
            [' XoXXXXXXXXXoXXoXXXXXXXXXoX '],
            [' XoX       XoXXoX       XoX '],
            [' XoXXXXXXXXXoXXoXXXXXXXXXoX '],
            [' XoooooooooooXXoooooooooooX '],
            [' XoXXXXXXXXXoXXoXXXXXXXXXoX '],
            [' XoX       XoXXoX       XoX '],
            [' XoXXXXXXXXXoXXoXXXXXXXXXoX '],
            [' Xoooooooooooo oooooooooooX '],
            [' XoXXXXXoXXXXXXXXXXoXXXXXoX '],
            [' XoX   XoX        XoX   XoX '],
            [' XoX   XoX        XoX   XoX '],
            [' XoX   XoXXXXXXXXXXoX   XoX '],
            [' XoX   XooooooooooooX   XoX '],
            [' XoX   XoXXXXXXXXXXoX   XoX '],
            [' XoX   XoX        XoX   XoX '],
            [' XoX   XoX        XoX   XoX '],
            [' XoXXXXXoXXXXXXXXXXoXXXXXoX '],
            [' XooooooooooooooooooooooooX '],
            [' XXXXXXXXXXXXXXXXXXXXXXXXXX '],
            ['                            '],
            ['                            '],
        ],
        ghosts: getRandomItem(ghostsPaths.maze3),
    },
    {
        pacman: { position: { x: 14, y: 7 } },
        mazeArray: [
            ['  XoX XoX          XoX XoX  '],
            ['  XoX XoX          XoX XoX  '],
            ['XXXoXXXoXXXXXXXXXXXXoXXXoXXX'],
            ['oooooooooooooooooooooooooooo'],
            ['XXXoXXXoXXXXXXXXXXXXoXXXoXXX'],
            ['  XoX XoX          XoX XoX  '],
            ['XXXoXXXoXXXXXXXXXXXXoXXXoXXX'],
            ['oooooooooooooo ooooooooooooo'],
            ['XXXoXXXoXXXXXXXXXXXXoXXXoXXX'],
            ['  XoX XoX          XoX XoX  '],
            ['  XoX XoX          XoX XoX  '],
            ['  XoX XoX  XX  X   XoX XoX  '],
            ['  XoX XoX   X X    XoX XoX  '],
            ['  XoX XoX   XX     XoX XoX  '],
            ['  XoX XoX   XX     XoX XoX  '],
            ['  XoX XoX   X X    XoX XoX  '],
            ['  XoX XoX   X  X   XoX XoX  '],
            ['  XoX XoX          XoX XoX  '],
            ['  XoX XoX          XoX XoX  '],
            ['XXXoXXXoXXXXXXXXXXXXoXXXoXXX'],
            ['oooooooooooooooooooooooooooo'],
            ['XXXoXXXoXXXXXXXXXXXXoXXXoXXX'],
            ['  XoX XoX          XoX XoX  '],
            ['XXXoXXXoXXXXXXXXXXXXoXXXoXXX'],
            ['oooooooooooooooooooooooooooo'],
            ['XXXoXXXoXXXXXXXXXXXXoXXXoXXX'],
            ['  XoX XoX          XoX XoX  '],
            ['  XoX XoX          XoX XoX  '],
        ],
        ghosts: getRandomItem(ghostsPaths.maze4),
    },
    {
        pacman: { position: { x: 14, y: 14 } },
        mazeArray: [
            ['ooX                      Xoo'],
            ['ooXX                    XXoo'],
            ['XooXXXXXXXXXXXXXXXXXXXXXXooX'],
            ['XXooooooooooooooooooooooooXX'],
            [' XXooXXXXXXXXXXXXXXXXXXoooX '],
            ['  XoooXX            XXooXoX '],
            ['  XoXooXX          XXooXXoX '],
            ['  XoXXooXX        XXooXXXoX '],
            ['  XoXXXooXX      XXooXX XoX '],
            ['  XoX XXooXX    XXooXX  XoX '],
            ['  XoX  XXooXX  XXooXX   XoX '],
            ['  XoX   XXooXXXXooXX    XoX '],
            ['  XoX    XXooXXooXX     XoX '],
            ['XXXoXXXXXXXXooooXXXXXXXXXoXX'],
            ['oooooooooooooo ooooooooooooo'],
            ['XXXoXXXXXXXXooooXXXXXXXXXoXX'],
            ['  XoX    XXooXXooXX     XoX '],
            ['  XoX   XXooXXXXooXX    XoX '],
            ['  XoX  XXooXX  XXooXX   XoX '],
            ['  XoX XXooXX    XXooXX  XoX '],
            ['  XoXXXooXX      XXooXX XoX '],
            ['  XoXXooXX        XXooXXXoX '],
            ['  XoXooXX          XXooXXoX '],
            ['  XoooXXXXXXXXXXXXXXXXooXoX '],
            [' XXoooooooooooooooooooooooX '],
            ['XXooXXXXXXXXXXXXXXXXXXXXooXX'],
            ['oooXX                  XXooo'],
            ['ooXX                    XXoo'],
        ],
        ghosts: getRandomItem(ghostsPaths.maze5),
    },
    {
        pacman: { position: { x: 14, y: 15 } },
        mazeArray: [
            ['    XoX              XoX    '],
            ['    XoX              XoX    '],
            ['  XXXoXXXXXXXXXXXXXXXXoXXX  '],
            ['  XooooooooooooooooooooooX  '],
            ['XXXoXXXoXXXXXXXXXXXXoXXXoXXX'],
            ['ooooX XoX          XoX Xoooo'],
            ['XXXoXXXoXXXXXXXXXX XoX XoXXX'],
            ['  XooooooooooooooX XoX XoX  '],
            ['  XoXXXXXXXXoXXXoX XoXXXoX  '],
            ['  XoX      XoX XoX XoooooX  '],
            ['  XoX      XoX XoX XoXXXoX  '],
            ['  XoXXXXXXXXoXXXoX XoX XoX  '],
            ['  XooooooooooooooX XoX XoX  '],
            ['  XoXXXoXXXXoXXXoX XoX XoX  '],
            ['  XoX XoX  XoXXXoXXXoXXXoX  '],
            ['  XoX XoX  Xoo ooooooooooX  '],
            ['  XoX XoX  XoXXXXXXXXXXXoX  '],
            ['  XoXXXoX  XoX         XoX  '],
            ['  XoooooX  XoX         XoX  '],
            ['  XoXXXoXXXXoXXXXXXXXXXXoX  '],
            ['  XoX XooooooooooooooooooX  '],
            ['XXXoX XoXXXXXXXXXXXXoXXXoXXX'],
            ['ooooX XoX          XoX Xoooo'],
            ['XXXoXXXoXXXXXXXXXXXXoXXXoXXX'],
            ['  XooooooooooooooooooooooX  '],
            ['  XXXoXXXXXXXXXXXXXXXXoXXX  '],
            ['    XoX              XoX    '],
            ['    XoX              XoX    '],
        ],
        ghosts: getRandomItem(ghostsPaths.maze6),
    },
    {
        pacman: { position: { x: 14, y: 12 } },
        mazeArray: [
            ['          XoX  XoX          '],
            [' XXXXXXXX XoX  XoX XXXXXXXX '],
            [' XooooooX XoX  XoX XooooooX '],
            [' XoXXXXoX XoX  XoX XoXXXXoX '],
            [' XooooooX XoX  XoX XooooooX '],
            [' XoXXXXoX XoXXXXoX XoXXXXoX '],
            [' XoX  XoX XooooooX XoX  XoX '],
            [' XoX  XoX XoXXXXoX XoX  XoX '],
            [' XoX  XoX XooooooX XoX  XoX '],
            [' XoXXXXoXXXoXXXXoXXXoXXXXoX '],
            [' XooooooooooooooooooooooooX '],
            ['XXoXXXXoXoXoXXXXoXoXoXXXXoXX'],
            ['oooooooooooooo ooooooooooooo'],
            ['XXoXXXXoXoXoXXXXoXoXoXXXXoXX'],
            ['XXoXXXXoXoXoXXXXoXoXoXXXXoXX'],
            ['oooooooooooooooooooooooooooo'],
            ['XXoXXXXoXoXoXXXXoXoXoXXXXoXX'],
            [' XooooooooooooooooooooooooX '],
            [' XoXXXXoXXXoXXXXoXXXoXXXXoX '],
            [' XoX  XoX XooooooX XoX  XoX '],
            [' XoX  XoX XoXXXXoX XoX  XoX '],
            [' XoX  XoX XooooooX XoX  XoX '],
            [' XoXXXXoX XoXXXXoX XoXXXXoX '],
            [' XooooooX XoX  XoX XooooooX '],
            [' XoXXXXoX XoX  XoX XoXXXXoX '],
            [' XooooooX XoX  XoX XooooooX '],
            [' XXXXXXXX XoX  XoX XXXXXXXX '],
            ['          XoX  XoX          '],
        ],
        ghosts: getRandomItem(ghostsPaths.maze7),
    },
    {
        pacman: { position: { x: 14, y: 13 } },
        mazeArray: [
            ['     XoX  XoX  XoX  XoX     '],
            ['XXXXXXoXXXXoXXXXoXXXXoXXXXXX'],
            ['oooooooooooooooooooooooooooo'],
            ['XXoXXXoXXXXoXXXXoXXXXoXXXoXX'],
            [' XoX XoX  XoX  XoX  XoX XoX '],
            [' XoX XoX  XoXXXXoX  XoX XoX '],
            [' XoX XoX  XooooooX  XoX XoX '],
            [' XoX XoX  XoXXXXoX  XoX XoX '],
            ['XXoXXXoXXXXoX  XoXXXXoXXXoXX'],
            ['ooooooooooooX  Xoooooooooooo'],
            ['XXXXXXoXXXXoX  XoXXXXoXXXXXX'],
            ['     XoX  XoX  XoX  XoX     '],
            ['     XoXXXXoXXXXoXXXXoX     '],
            ['     Xoooooooo oooooooX     '],
            ['     XoXXXXXXXXXXXXXXoX     '],
            ['     XoX XooooooooX XoX     '],
            ['     XoX XoXXXXXXoX XoX     '],
            ['XXXXXXoXXXoX    XoXXXoXXXXXX'],
            ['oooooooooooX    Xooooooooooo'],
            ['XXoXXXoXXXoX    XoXXXoXXXoXX'],
            [' XoX XoX XoXXXXXXoX XoX XoX '],
            [' XoX XoX XooooooooX XoX XoX '],
            ['XXoXXXoXXXXXXXXXXXXXXoXXXoXX'],
            ['oooooooooooooooooooooooooooo'],
            ['XXXXXXoXXXXoXXXXoXXXXoXXXXXX'],
            ['     XoX  XoX  XoX  XoX     '],
            ['     XoX  XoX  XoX  XoX     '],
            ['     XoX  XoX  XoX  XoX     '],
        ],
        ghosts: getRandomItem(ghostsPaths.maze8),
    },
    {
        pacman: { position: { x: 14, y: 14 } },
        mazeArray: [
            ['           XoXXoX           '],
            [' XXXXXXXXX XoXXoX XXXXXXXXX '],
            [' XoooooooX XooooX XoooooooX '],
            [' XoXXXXXoX XoXXoX XoXXXXXoX '],
            [' XoX   XoX XoXXoX XoX   XoX '],
            [' XoX   XoX XooooX XoX   XoX '],
            [' XoX   XoX XoXXoX XoX   XoX '],
            [' XoXXXXXoXXXoXXoXXXoXXXXXoX '],
            [' XooooooooooooooooooooooooX '],
            [' XXXXXXXoXXXXXoXXXXoXXXXXXX '],
            ['       XoX   XoX  XoX       '],
            ['XXXXXXXXoX   XoX  XoXXXXXXXX'],
            ['oooooooooX  XXoXXXXooooooooo'],
            ['XXoXXoXXoXXXXoooooooXXoXXoXX'],
            ['XXoXXoXXoooooo XXXXoXXoXXoXX'],
            ['oooooooooXXXXoXX  Xooooooooo'],
            ['XXXXXXXXoX  XoX   XoXXXXXXXX'],
            ['       XoX  XoX   XoX       '],
            [' XXXXXXXoXXXXoXXXXXoXXXXXXX '],
            [' XooooooooooooooooooooooooX '],
            [' XoXXXXXoXXXoXXoXXXoXXXXXoX '],
            [' XoX   XoX XoXXoX XoX   XoX '],
            [' XoX   XoX XooooX XoX   XoX '],
            [' XoX   XoX XoXXoX XoX   XoX '],
            [' XoXXXXXoX XoXXoX XoXXXXXoX '],
            [' XoooooooX XooooX XoooooooX '],
            [' XXXXXXXXX XoXXoX XXXXXXXXX '],
            ['           XoXXoX           '],
        ],
        ghosts: getRandomItem(ghostsPaths.maze9),
    },
    {
        pacman: { position: { x: 12, y: 14 } },
        mazeArray: [
            ['                            '],
            [' XXXXXXXXXXXXXXXXXXXXXXXXXX '],
            [' XooooooooooooooooooooooooX '],
            [' XoXoXoXoXoXoXXoXoXoXoXoXoX '],
            [' XooooooooooooooooooooooooX '],
            [' XoXXoXXoXXoXXXXoXXoXXoXXoX '],
            [' XoXXoXXoXXoXXXXoXXoXXoXXoX '],
            [' XooooooooooooooooooooooooX '],
            [' XoXXXoXXXoXXXXXXoXXXoXXXoX '],
            [' XoXXXoXXXooooooooXXXoXXXoX '],
            [' XoXXXoXXXoXoXXoXoXXXoXXXoX '],
            [' XooooooooooooooooooooooooX '],
            [' XoXXXXoXXXXoXXoXXXXoXXXXoX '],
            [' XoXXXXoXXXXoXXoXXXXoXXXXoX '],
            [' XoXXXXoXXXX XXoXXXXoXXXXoX '],
            [' XoXXXXoXXXXoXXoXXXXoXXXXoX '],
            [' XooooooooooooooooooooooooX '],
            [' XoXXXoXXXoXoXXoXoXXXoXXXoX '],
            [' XoXXXoXXXooooooooXXXoXXXoX '],
            [' XoXXXoXXXoXXXXXXoXXXoXXXoX '],
            [' XooooooooooooooooooooooooX '],
            [' XoXXoXXoXXoXXXXoXXoXXoXXoX '],
            [' XoXXoXXoXXoXXXXoXXoXXoXXoX '],
            [' XooooooooooooooooooooooooX '],
            [' XoXoXoXoXoXoXXoXoXoXoXoXoX '],
            [' XooooooooooooooooooooooooX '],
            [' XXXXXXXXXXXXXXXXXXXXXXXXXX '],
            ['                            '],
        ],
        ghosts: getRandomItem(ghostsPaths.maze10),
    },
];
var GAME_SETTINGS = {
    customSimple: {
        pacman: { position: { x: 1, y: 1 } },
        mazeArray: [
            ['XXXXXXXX     '],
            ['XooooooX     '],
            ['XXXXXXoX     '],
            ['     XoX     '],
            ['     XoX     '],
            ['     XoX     '],
            ['     XoX     '],
            ['  XXXXoXXXX  '],
            ['  X   o   X  '],
            ['  XXXXoXXXX  '],
            ['     XoX     '],
            ['     XoX     '],
            ['     XoX     '],
            ['     XoX     '],
            ['     XoXXXXXX'],
            ['     XooooooX'],
            ['     XXXXXXXX'],
        ],
        ghosts: [
            {
                position: { x: 3, y: 8 },
                getMoveTarget: patrolGhostMoves([
                    { x: 3, y: 8 },
                    { x: 9, y: 8 },
                ]),
                canTurnAround: !0,
                velocity: 1,
            },
        ],
    },
    customCross: {
        pacman: { position: { x: 6, y: 7 } },
        mazeArray: [
            ['     X X     '],
            ['     XoX     '],
            ['     XoX     '],
            ['     XoX     '],
            ['     XoX     '],
            ['     XoX     '],
            ['XXXXXXoXXXXXX'],
            ['   ooooooo   '],
            ['XXXXXXoXXXXXX'],
            ['     XoX     '],
            ['     XoX     '],
            ['     XoX     '],
            ['     XoX     '],
            ['     XoX     '],
            ['     X X     '],
        ],
        ghosts: [],
    },
    firstTask: {
        pacman: { position: { x: 0, y: 1 }, initialDirection: 'right' },
        mazeArray: [['XXXXXXXXXXXXXXXX'], ['       ooooooo  '], ['XXXXXXXXXXXXXXXX']],
        ghosts: [],
    },
    secondTask: getRandomItem(secondLevel),
    thirdTask: getRandomItem(thirdLevel),
};
Object.values(GAME_SETTINGS).forEach((settings) => {
    settings.mazeArray.forEach((row, rowIndex) => {
        settings.mazeArray[rowIndex] = row[0]?.split('') ?? [];
    });
});
export { GAME_SETTINGS };
